name: CI

on:
  push:
    branches: [ tutorial ]
  pull_request:
    branches: [ tutorial ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/tutorial'
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      # Ensure you're using the specific Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build project
      - name: Build
        run: npm run build

      # Run tests
      - name: Test
        run: npm run test

      # Deploy using rsync
      - name: Rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/my-app/
          remote_host: ec2-18-199-86-33.eu-central-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
